### ISSUE TITLE
"Can't customize entry files?"

### ISSUE THREAD

**Issue by yyong008** [pcattori/remix-template-vite#4]
I revamped my project and, as a result, customized two files: `entry.client.ts` and `entry.server.ts`. When I start the Vite server, I encounter an issue, and I'm not sure if it's due to my configuration or if I'm unable to make modifications. I believe this part might require more detailed documentation for clarification.

`[vite] Internal server error: Cannot import non-asset file /app/entry.server.tsx which is inside /public. JS/CSS files inside /public are copied as-is on build and can only be referenced via <script src> or <link href> in html. If you want to get the URL of that file, use /app/entry.server.tsx?url instead.`

**Comment by pcattori** [comment]
Can't reproduce. Can you share a reproduction in StackBlitz/CodeSandbox or a link to a repro repo in GitHub?

**Comment by yyong008** [comment]
I am conducting cross-platform testing, and there may be some issues.

this repo: [remix-vite-demo](https://github.com/yyong008/remix-vite-demo)

This is my test:

Because of using `Windows11`  and `pnpm` as the package management tool, you will receive the following error message:

```sh
[vite] Internal server error: ENOENT: no such file or directory, realpath '\remix-vite\node_modules\.pnpm\@remix-run+dev@0.0.0-nightly-9e30e56-20231022_@remix-run+serve@0.0.0-nightly-9e30e56-20231022_ezfusfotaecm5zinnsz5jju7bu\node_modules\@remix-run\dev\dist\config\defaults\entry.server.node.tsx'
  Plugin: vite:import-analysis
  File: virtual:server-entry
```

Later, I also tested Windows WSL and macOS 13.5, and they were both functioning normally.

**Comment by pcattori** [comment]
@yyong008 did this get fixed for you?

**Comment by yyong008** [comment]
> did this get fixed for you?
Creating a new pnpm project with create-remix@nightly, I noticed that there have been changes in the dependencies. I'm not sure if your team has fixed them. My pnpm setup on Windows 11 seems to be working fine, so it might require further testing on my part. However, I have other issues to address right now, so I'm closing this for the time being.
